# Generated by Django 6.0.2 on 2026-04-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_order_items_remove_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='discount_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subtotal',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tax_amount',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Sales tax', max_digits=10),
        ),
    ]
