# Generated by Django 6.0.2 on 2026-04-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_transaction_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
