# Generated by Django 6.0.2 on 2026-04-17 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='cashier',
        ),
    ]
